"""initial schema

Revision ID: acd800719a81
Revises:
Create Date: 2026-08-31 17:23:20.475101
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "acd800719a81"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "units_of_measure",
        sa.Column("code", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=64), nullable=False),
        sa.Column("decimal_places", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_units_of_measure")),
        sa.UniqueConstraint("code", name=op.f("uq_units_of_measure_code")),
    )
    op.create_table(
        "warehouses",
        sa.Column("code", sa.String(length=32), nullable=False),
        sa.Column("name", sa.String(length=160), nullable=False),
        sa.Column("timezone", sa.String(length=64), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_warehouses")),
        sa.UniqueConstraint("code", name=op.f("uq_warehouses_code")),
    )
    op.create_table(
        "items",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("sku", sa.String(length=80), nullable=False),
        sa.Column("description", sa.String(length=240), nullable=False),
        sa.Column(
            "inventory_path",
            sa.Enum(
                "SPECTRUM_MANAGED",
                "LOCAL_GENERAL_USE",
                name="inventorypath",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("spectrum_item_id", sa.String(length=120), nullable=True),
        sa.Column("uom_id", sa.Uuid(), nullable=False),
        sa.Column("reorder_point", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_items_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_items_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_items")),
        sa.UniqueConstraint("spectrum_item_id", name=op.f("uq_items_spectrum_item_id")),
        sa.UniqueConstraint("warehouse_id", "sku", name=op.f("uq_items_warehouse_id")),
    )
    op.create_index(op.f("ix_items_warehouse_id"), "items", ["warehouse_id"], unique=False)
    op.create_table(
        "locations",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("code", sa.String(length=80), nullable=False),
        sa.Column("zone", sa.String(length=40), nullable=False),
        sa.Column("aisle", sa.String(length=40), nullable=False),
        sa.Column("bay", sa.String(length=40), nullable=False),
        sa.Column("shelf", sa.String(length=40), nullable=False),
        sa.Column("position", sa.String(length=40), nullable=False),
        sa.Column("pick_sequence", sa.Integer(), nullable=False),
        sa.Column("is_staging", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_locations_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_locations")),
        sa.UniqueConstraint("warehouse_id", "code", name=op.f("uq_locations_warehouse_id")),
    )
    op.create_index(
        op.f("ix_locations_pick_sequence"), "locations", ["pick_sequence"], unique=False
    )
    op.create_index(op.f("ix_locations_warehouse_id"), "locations", ["warehouse_id"], unique=False)
    op.create_table(
        "outbox_events",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("event_type", sa.String(length=80), nullable=False),
        sa.Column("aggregate_id", sa.Uuid(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "SUCCEEDED",
                "FAILED",
                "REQUIRES_REVIEW",
                name="outboxstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("attempt_count", sa.Integer(), nullable=False),
        sa.Column("available_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_outbox_events_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_events")),
    )
    op.create_index(
        op.f("ix_outbox_events_aggregate_id"), "outbox_events", ["aggregate_id"], unique=False
    )
    op.create_index(
        op.f("ix_outbox_events_available_at"), "outbox_events", ["available_at"], unique=False
    )
    op.create_index(op.f("ix_outbox_events_status"), "outbox_events", ["status"], unique=False)
    op.create_index(
        op.f("ix_outbox_events_warehouse_id"), "outbox_events", ["warehouse_id"], unique=False
    )
    op.create_table(
        "users",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("username", sa.String(length=80), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_users_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("warehouse_id", "username", name=op.f("uq_users_warehouse_id")),
    )
    op.create_index(op.f("ix_users_warehouse_id"), "users", ["warehouse_id"], unique=False)
    op.create_table(
        "approved_alternates",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("alternate_item_id", sa.Uuid(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["alternate_item_id"],
            ["items.id"],
            name=op.f("fk_approved_alternates_alternate_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_approved_alternates_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_approved_alternates_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_approved_alternates")),
        sa.UniqueConstraint(
            "item_id", "alternate_item_id", name=op.f("uq_approved_alternates_item_id")
        ),
    )
    op.create_index(
        op.f("ix_approved_alternates_warehouse_id"),
        "approved_alternates",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "audit_events",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("action", sa.String(length=80), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=False),
        sa.Column("entity_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("changes", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_audit_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_audit_events_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index(op.f("ix_audit_events_action"), "audit_events", ["action"], unique=False)
    op.create_index(
        op.f("ix_audit_events_actor_user_id"), "audit_events", ["actor_user_id"], unique=False
    )
    op.create_index(op.f("ix_audit_events_entity_id"), "audit_events", ["entity_id"], unique=False)
    op.create_index(
        op.f("ix_audit_events_entity_type"), "audit_events", ["entity_type"], unique=False
    )
    op.create_index(
        op.f("ix_audit_events_warehouse_id"), "audit_events", ["warehouse_id"], unique=False
    )
    op.create_table(
        "employee_recipients",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("employee_number", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=160), nullable=False),
        sa.Column("linked_user_id", sa.Uuid(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["linked_user_id"],
            ["users.id"],
            name=op.f("fk_employee_recipients_linked_user_id_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_employee_recipients_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_employee_recipients")),
        sa.UniqueConstraint(
            "warehouse_id", "employee_number", name=op.f("uq_employee_recipients_warehouse_id")
        ),
    )
    op.create_index(
        op.f("ix_employee_recipients_warehouse_id"),
        "employee_recipients",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "map_grid_cells",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("row_index", sa.Integer(), nullable=False),
        sa.Column("column_index", sa.Integer(), nullable=False),
        sa.Column("label", sa.String(length=80), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_map_grid_cells_location_id_locations"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_map_grid_cells_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_map_grid_cells")),
        sa.UniqueConstraint("location_id", name=op.f("uq_map_grid_cells_location_id")),
        sa.UniqueConstraint(
            "warehouse_id", "row_index", "column_index", name=op.f("uq_map_grid_cells_warehouse_id")
        ),
    )
    op.create_index(
        op.f("ix_map_grid_cells_warehouse_id"), "map_grid_cells", ["warehouse_id"], unique=False
    )
    op.create_table(
        "notifications",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=160), nullable=False),
        sa.Column("message", sa.String(length=500), nullable=False),
        sa.Column("entity_type", sa.String(length=80), nullable=True),
        sa.Column("entity_id", sa.Uuid(), nullable=True),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_notifications_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_notifications_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    op.create_index(op.f("ix_notifications_user_id"), "notifications", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_notifications_warehouse_id"), "notifications", ["warehouse_id"], unique=False
    )
    op.create_table(
        "outbox_attempts",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("outbox_event_id", sa.Uuid(), nullable=False),
        sa.Column("succeeded", sa.Boolean(), nullable=False),
        sa.Column("response_reference", sa.String(length=160), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["outbox_event_id"],
            ["outbox_events.id"],
            name=op.f("fk_outbox_attempts_outbox_event_id_outbox_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_outbox_attempts_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox_attempts")),
    )
    op.create_index(
        op.f("ix_outbox_attempts_outbox_event_id"),
        "outbox_attempts",
        ["outbox_event_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_outbox_attempts_warehouse_id"), "outbox_attempts", ["warehouse_id"], unique=False
    )
    op.create_table(
        "role_assignments",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column(
            "role",
            sa.Enum(
                "EMPLOYEE",
                "FOREMAN",
                "WAREHOUSE_WORKER",
                "INVENTORY_MANAGER",
                "SYSTEM_ADMINISTRATOR",
                name="role",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_role_assignments_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_role_assignments_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_role_assignments")),
        sa.UniqueConstraint("user_id", "role", name=op.f("uq_role_assignments_user_id")),
    )
    op.create_index(
        op.f("ix_role_assignments_user_id"), "role_assignments", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_role_assignments_warehouse_id"), "role_assignments", ["warehouse_id"], unique=False
    )
    op.create_table(
        "stock_positions",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=False),
        sa.Column("on_hand", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("quarantined_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("on_hand >= 0", name=op.f("ck_stock_positions_on_hand_nonnegative")),
        sa.CheckConstraint(
            "quarantined_qty <= on_hand", name=op.f("ck_stock_positions_quarantined_within_on_hand")
        ),
        sa.CheckConstraint(
            "quarantined_qty >= 0", name=op.f("ck_stock_positions_quarantined_nonnegative")
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_stock_positions_item_id_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_stock_positions_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_stock_positions_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_stock_positions")),
        sa.UniqueConstraint(
            "warehouse_id", "item_id", "location_id", name=op.f("uq_stock_positions_warehouse_id")
        ),
    )
    op.create_index(
        op.f("ix_stock_positions_item_id"), "stock_positions", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_positions_location_id"), "stock_positions", ["location_id"], unique=False
    )
    op.create_index(
        op.f("ix_stock_positions_warehouse_id"), "stock_positions", ["warehouse_id"], unique=False
    )
    op.create_table(
        "unit_conversions",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("from_uom_id", sa.Uuid(), nullable=False),
        sa.Column("to_uom_id", sa.Uuid(), nullable=False),
        sa.Column("factor", sa.Numeric(precision=18, scale=6), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_unit_conversions_from_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_unit_conversions_item_id_items"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["to_uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_unit_conversions_to_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_unit_conversions_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_unit_conversions")),
        sa.UniqueConstraint(
            "item_id", "from_uom_id", "to_uom_id", name=op.f("uq_unit_conversions_item_id")
        ),
    )
    op.create_index(
        op.f("ix_unit_conversions_warehouse_id"), "unit_conversions", ["warehouse_id"], unique=False
    )
    op.create_table(
        "user_sessions",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("csrf_hash", sa.String(length=64), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_user_sessions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_user_sessions_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_user_sessions")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_user_sessions_token_hash")),
    )
    op.create_index(
        op.f("ix_user_sessions_expires_at"), "user_sessions", ["expires_at"], unique=False
    )
    op.create_index(op.f("ix_user_sessions_user_id"), "user_sessions", ["user_id"], unique=False)
    op.create_index(
        op.f("ix_user_sessions_warehouse_id"), "user_sessions", ["warehouse_id"], unique=False
    )
    op.create_table(
        "inventory_events",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "RECEIPT",
                "GENERAL_USE_WITHDRAWAL",
                "MATERIAL_ISSUE",
                "RETURN",
                "MOVE",
                "COUNT_ADJUSTMENT",
                "QUARANTINE",
                "RELEASE",
                "MANAGER_CORRECTION",
                name="inventoryeventtype",
                native_enum=False,
                length=40,
            ),
            nullable=False,
        ),
        sa.Column("actor_user_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=True),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("location_id", sa.Uuid(), nullable=True),
        sa.Column("destination_location_id", sa.Uuid(), nullable=True),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("uom_id", sa.Uuid(), nullable=False),
        sa.Column("reason", sa.String(length=500), nullable=True),
        sa.Column("source_workflow", sa.String(length=80), nullable=False),
        sa.Column("reference_id", sa.Uuid(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_user_id"],
            ["users.id"],
            name=op.f("fk_inventory_events_actor_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["destination_location_id"],
            ["locations.id"],
            name=op.f("fk_inventory_events_destination_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_inventory_events_item_id_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["location_id"],
            ["locations.id"],
            name=op.f("fk_inventory_events_location_id_locations"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["employee_recipients.id"],
            name=op.f("fk_inventory_events_recipient_id_employee_recipients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["uom_id"],
            ["units_of_measure.id"],
            name=op.f("fk_inventory_events_uom_id_units_of_measure"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_inventory_events_warehouse_id_warehouses"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_inventory_events")),
    )
    op.create_index(
        op.f("ix_inventory_events_actor_user_id"),
        "inventory_events",
        ["actor_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_inventory_events_event_type"), "inventory_events", ["event_type"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_events_item_id"), "inventory_events", ["item_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_events_reference_id"), "inventory_events", ["reference_id"], unique=False
    )
    op.create_index(
        op.f("ix_inventory_events_warehouse_id"), "inventory_events", ["warehouse_id"], unique=False
    )
    op.create_table(
        "material_requests",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("request_number", sa.String(length=40), nullable=False),
        sa.Column("creator_user_id", sa.Uuid(), nullable=False),
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("claimed_by_user_id", sa.Uuid(), nullable=True),
        sa.Column(
            "state",
            sa.Enum(
                "DRAFT",
                "SUBMITTED",
                "CLAIMED",
                "IN_PROGRESS",
                "READY",
                "PARTIALLY_FULFILLED",
                "COMPLETED",
                "ON_HOLD",
                "CANCELLED",
                name="requeststate",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("NORMAL", "URGENT", name="requestpriority", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("urgent_reason", sa.String(length=500), nullable=True),
        sa.Column("job_number", sa.String(length=80), nullable=True),
        sa.Column("cost_code", sa.String(length=80), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["claimed_by_user_id"],
            ["users.id"],
            name=op.f("fk_material_requests_claimed_by_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["creator_user_id"],
            ["users.id"],
            name=op.f("fk_material_requests_creator_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["employee_recipients.id"],
            name=op.f("fk_material_requests_recipient_id_employee_recipients"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_material_requests_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_material_requests")),
        sa.UniqueConstraint("request_number", name=op.f("uq_material_requests_request_number")),
    )
    op.create_index(
        op.f("ix_material_requests_warehouse_id"),
        "material_requests",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "fulfillment_batches",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("worker_user_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("handed_off_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["material_requests.id"],
            name=op.f("fk_fulfillment_batches_request_id_material_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_fulfillment_batches_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["worker_user_id"],
            ["users.id"],
            name=op.f("fk_fulfillment_batches_worker_user_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_fulfillment_batches")),
    )
    op.create_index(
        op.f("ix_fulfillment_batches_request_id"),
        "fulfillment_batches",
        ["request_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_fulfillment_batches_warehouse_id"),
        "fulfillment_batches",
        ["warehouse_id"],
        unique=False,
    )
    op.create_table(
        "offline_grants",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("device_id", sa.String(length=160), nullable=False),
        sa.Column("request_version", sa.Integer(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["material_requests.id"],
            name=op.f("fk_offline_grants_request_id_material_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_offline_grants_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_offline_grants_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_grants")),
    )
    op.create_index(
        op.f("ix_offline_grants_warehouse_id"), "offline_grants", ["warehouse_id"], unique=False
    )
    op.create_table(
        "request_lines",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("request_id", sa.Uuid(), nullable=False),
        sa.Column("item_id", sa.Uuid(), nullable=False),
        sa.Column("requested_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("allocated_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("picked_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("issued_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("cancelled_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("backordered_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "allocated_qty >= 0", name=op.f("ck_request_lines_allocated_nonnegative")
        ),
        sa.CheckConstraint(
            "backordered_qty >= 0", name=op.f("ck_request_lines_backordered_nonnegative")
        ),
        sa.CheckConstraint(
            "cancelled_qty >= 0", name=op.f("ck_request_lines_cancelled_nonnegative")
        ),
        sa.CheckConstraint("issued_qty >= 0", name=op.f("ck_request_lines_issued_nonnegative")),
        sa.CheckConstraint("picked_qty >= 0", name=op.f("ck_request_lines_picked_nonnegative")),
        sa.CheckConstraint("requested_qty > 0", name=op.f("ck_request_lines_requested_positive")),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["items.id"],
            name=op.f("fk_request_lines_item_id_items"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["request_id"],
            ["material_requests.id"],
            name=op.f("fk_request_lines_request_id_material_requests"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_request_lines_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_request_lines")),
    )
    op.create_index(
        op.f("ix_request_lines_request_id"), "request_lines", ["request_id"], unique=False
    )
    op.create_index(
        op.f("ix_request_lines_warehouse_id"), "request_lines", ["warehouse_id"], unique=False
    )
    op.create_table(
        "allocations",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("request_line_id", sa.Uuid(), nullable=False),
        sa.Column("stock_position_id", sa.Uuid(), nullable=False),
        sa.Column("quantity", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("picked_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("issued_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("released_qty", sa.Numeric(precision=18, scale=3), nullable=False),
        sa.Column("pick_confirmed", sa.Boolean(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "issued_qty + released_qty <= quantity",
            name=op.f("ck_allocations_closed_within_quantity"),
        ),
        sa.CheckConstraint(
            "issued_qty <= picked_qty", name=op.f("ck_allocations_issued_within_picked")
        ),
        sa.CheckConstraint("issued_qty >= 0", name=op.f("ck_allocations_issued_nonnegative")),
        sa.CheckConstraint(
            "picked_qty <= quantity", name=op.f("ck_allocations_picked_within_quantity")
        ),
        sa.CheckConstraint("picked_qty >= 0", name=op.f("ck_allocations_picked_nonnegative")),
        sa.CheckConstraint("quantity > 0", name=op.f("ck_allocations_quantity_positive")),
        sa.CheckConstraint("released_qty >= 0", name=op.f("ck_allocations_released_nonnegative")),
        sa.ForeignKeyConstraint(
            ["request_line_id"],
            ["request_lines.id"],
            name=op.f("fk_allocations_request_line_id_request_lines"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["stock_position_id"],
            ["stock_positions.id"],
            name=op.f("fk_allocations_stock_position_id_stock_positions"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_allocations_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_allocations")),
    )
    op.create_index(
        op.f("ix_allocations_request_line_id"), "allocations", ["request_line_id"], unique=False
    )
    op.create_index(
        op.f("ix_allocations_stock_position_id"), "allocations", ["stock_position_id"], unique=False
    )
    op.create_index(
        op.f("ix_allocations_warehouse_id"), "allocations", ["warehouse_id"], unique=False
    )
    op.create_table(
        "offline_commands",
        sa.Column("warehouse_id", sa.Uuid(), nullable=False),
        sa.Column("grant_id", sa.Uuid(), nullable=False),
        sa.Column("client_command_id", sa.Uuid(), nullable=False),
        sa.Column("sequence", sa.Integer(), nullable=False),
        sa.Column("command_type", sa.String(length=80), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPLIED",
                "CONFLICT",
                "REJECTED",
                name="offlinecommandstatus",
                native_enum=False,
                length=20,
            ),
            nullable=False,
        ),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["grant_id"],
            ["offline_grants.id"],
            name=op.f("fk_offline_commands_grant_id_offline_grants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["warehouse_id"],
            ["warehouses.id"],
            name=op.f("fk_offline_commands_warehouse_id_warehouses"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_offline_commands")),
        sa.UniqueConstraint(
            "warehouse_id", "client_command_id", name=op.f("uq_offline_commands_warehouse_id")
        ),
    )
    op.create_index(
        op.f("ix_offline_commands_warehouse_id"), "offline_commands", ["warehouse_id"], unique=False
    )
    # ### end Alembic commands ###
    if op.get_bind().dialect.name == "postgresql":
        op.execute(
            """
            CREATE FUNCTION reject_immutable_event_change()
            RETURNS trigger AS $$
            BEGIN
                RAISE EXCEPTION 'Event history is append-only';
            END;
            $$ LANGUAGE plpgsql
            """
        )
        for table_name in ("audit_events", "inventory_events"):
            op.execute(
                f"""
                CREATE TRIGGER {table_name}_immutable
                BEFORE UPDATE OR DELETE ON {table_name}
                FOR EACH ROW EXECUTE FUNCTION reject_immutable_event_change()
                """
            )


def downgrade() -> None:
    if op.get_bind().dialect.name == "postgresql":
        for table_name in ("audit_events", "inventory_events"):
            op.execute(f"DROP TRIGGER IF EXISTS {table_name}_immutable ON {table_name}")
        op.execute("DROP FUNCTION IF EXISTS reject_immutable_event_change()")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_offline_commands_warehouse_id"), table_name="offline_commands")
    op.drop_table("offline_commands")
    op.drop_index(op.f("ix_allocations_warehouse_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_stock_position_id"), table_name="allocations")
    op.drop_index(op.f("ix_allocations_request_line_id"), table_name="allocations")
    op.drop_table("allocations")
    op.drop_index(op.f("ix_request_lines_warehouse_id"), table_name="request_lines")
    op.drop_index(op.f("ix_request_lines_request_id"), table_name="request_lines")
    op.drop_table("request_lines")
    op.drop_index(op.f("ix_offline_grants_warehouse_id"), table_name="offline_grants")
    op.drop_table("offline_grants")
    op.drop_index(op.f("ix_fulfillment_batches_warehouse_id"), table_name="fulfillment_batches")
    op.drop_index(op.f("ix_fulfillment_batches_request_id"), table_name="fulfillment_batches")
    op.drop_table("fulfillment_batches")
    op.drop_index(op.f("ix_material_requests_warehouse_id"), table_name="material_requests")
    op.drop_table("material_requests")
    op.drop_index(op.f("ix_inventory_events_warehouse_id"), table_name="inventory_events")
    op.drop_index(op.f("ix_inventory_events_reference_id"), table_name="inventory_events")
    op.drop_index(op.f("ix_inventory_events_item_id"), table_name="inventory_events")
    op.drop_index(op.f("ix_inventory_events_event_type"), table_name="inventory_events")
    op.drop_index(op.f("ix_inventory_events_actor_user_id"), table_name="inventory_events")
    op.drop_table("inventory_events")
    op.drop_index(op.f("ix_user_sessions_warehouse_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_user_id"), table_name="user_sessions")
    op.drop_index(op.f("ix_user_sessions_expires_at"), table_name="user_sessions")
    op.drop_table("user_sessions")
    op.drop_index(op.f("ix_unit_conversions_warehouse_id"), table_name="unit_conversions")
    op.drop_table("unit_conversions")
    op.drop_index(op.f("ix_stock_positions_warehouse_id"), table_name="stock_positions")
    op.drop_index(op.f("ix_stock_positions_location_id"), table_name="stock_positions")
    op.drop_index(op.f("ix_stock_positions_item_id"), table_name="stock_positions")
    op.drop_table("stock_positions")
    op.drop_index(op.f("ix_role_assignments_warehouse_id"), table_name="role_assignments")
    op.drop_index(op.f("ix_role_assignments_user_id"), table_name="role_assignments")
    op.drop_table("role_assignments")
    op.drop_index(op.f("ix_outbox_attempts_warehouse_id"), table_name="outbox_attempts")
    op.drop_index(op.f("ix_outbox_attempts_outbox_event_id"), table_name="outbox_attempts")
    op.drop_table("outbox_attempts")
    op.drop_index(op.f("ix_notifications_warehouse_id"), table_name="notifications")
    op.drop_index(op.f("ix_notifications_user_id"), table_name="notifications")
    op.drop_table("notifications")
    op.drop_index(op.f("ix_map_grid_cells_warehouse_id"), table_name="map_grid_cells")
    op.drop_table("map_grid_cells")
    op.drop_index(op.f("ix_employee_recipients_warehouse_id"), table_name="employee_recipients")
    op.drop_table("employee_recipients")
    op.drop_index(op.f("ix_audit_events_warehouse_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_type"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_entity_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_actor_user_id"), table_name="audit_events")
    op.drop_index(op.f("ix_audit_events_action"), table_name="audit_events")
    op.drop_table("audit_events")
    op.drop_index(op.f("ix_approved_alternates_warehouse_id"), table_name="approved_alternates")
    op.drop_table("approved_alternates")
    op.drop_index(op.f("ix_users_warehouse_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_outbox_events_warehouse_id"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_status"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_available_at"), table_name="outbox_events")
    op.drop_index(op.f("ix_outbox_events_aggregate_id"), table_name="outbox_events")
    op.drop_table("outbox_events")
    op.drop_index(op.f("ix_locations_warehouse_id"), table_name="locations")
    op.drop_index(op.f("ix_locations_pick_sequence"), table_name="locations")
    op.drop_table("locations")
    op.drop_index(op.f("ix_items_warehouse_id"), table_name="items")
    op.drop_table("items")
    op.drop_table("warehouses")
    op.drop_table("units_of_measure")
    # ### end Alembic commands ###
